version: '2' 
services:
  app:
    build: 
      context: .
    volumes:
      - ./:/usr/src/app
    links:
      - mysql:mysqlhost
  mysql:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: root
